site_name: Global Public Data API Hub
site_description: FastAPI-based hub for global public datasets with unified API and reproducible pipelines
site_author: Kalyana Krishna Kondapalli
theme:
  name: material
nav:
  - Home: index.md
  - Installation: installation.md
  - API: api.md
  - Connectors: connectors.md
  - Demo Notebook: demo.md
  - JOSS Paper: joss.md
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
